version: '3'
services:
  sonarqube:
    image: sonarqube:9.9.4-community
    ports:
      - "9100:9000"


#  psql:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    restart: on-failure
#    environment:
#      - POSTGRES_DB=posts
#      - POSTGRES_USER=postgre_user
#      - POSTGRES_PASSWORD=postgre_secret_password
#    volumes:
#      - database-data:/var/lib/postgresql/data/
#
#
#  minio:
#    image: bitnami/minio:latest
#    ports:
#      - "9100:9000"
#      - "9101:9001"
#    volumes:
#      - minio_storage:/data
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin
#
#
#  zipkin:
#    image: "openzipkin/zipkin"
#    ports:
#      - "9511:9411"
#
#
#volumes:
#  database-data:
#  minio_storage: