namespace: &namespace default


configMap:
  name: post-service-config


database:
  name: posts
  username: postgre_user
  password: postgre_secret_password
  storagePath: /post-service/postgresql-storage-default
  deployment:
    name: deployment-postgresql
    namespace: *namespace
  replicas:
    count: 1
  label:
    app: postgresql
  container:
    name: postgresql-container
    port: 5432
  image:
    name: postgres
    version: latest
  service:
    name: service-postgresql
    port: 5432
    nodePort: 31200


backendPostService:
  label:
    app: backend-post-service
  deployment:
    name: deployment-backend-post-service
    namespace: *namespace
  replicas:
    count: 1
  container:
    name: backend-post-service-container
    port: 8081
  image:
    name: euchekavelo/backend-post-service
    version: latest-default
  service:
    name: service-backend-post-service
    port: 8081
    nodePort: 31201
  datasource:
    prefixConnectionUrl: jdbc:postgresql


s3:
  label:
    app: minio
  service:
    name: minio-service
    ui:
      port: 9001
      nodePort: 31202
    server:
      port: 9000
      nodePort: 31203
  ingress:
    name: minio-ingress
    host: post-service-minio-default.local
  statefulSet:
    name: minio-statefulset
    container:
      name: minio-container
      ui:
        port: 9001
      server:
        port: 9000
    image:
      name: quay.io/minio/minio
      version: latest
  volume:
    name: minio-pvc
    storagePath: /post-service/minio-storage-default
  minioRegion: ru-center
  minioBucketName: posts


zipkin:
  label:
    app: zipkin-post-service
  deployment:
    name: deployment-zipkin-post-service
    namespace: *namespace
  replicas:
    count: 1
  container:
    name: zipkin-post-service-container
    port: 9411
  image:
    name: openzipkin/zipkin
  service:
    name: service-zipkin-post-service
    port: 9411
    nodePort: 31204


ingress:
  name: backend-post-service-ingress
  host: post-service-default.local