namespace: &namespace dev

database:
  storagePath: /postgresql-storage-dev
  service:
    nodePort: 31210


backendPostService:
  image:
    version: latest-dev
  service:
    nodePort: 31211


s3:
  service:
    ui:
      nodePort: 31212
    server:
      nodePort: 31213
  ingress:
    host: post-service-minio-dev.local
  volume:
    storagePath: /post-service/minio-storage-dev


ingress:
  host: post-service-dev.local