namespace: &namespace prod

database:
  storagePath: /postgresql-storage-prod
  service:
    nodePort: 31240


backendPostService:
  image:
    version: latest-prod
  service:
    nodePort: 31241


s3:
  service:
    ui:
      nodePort: 31242
    server:
      nodePort: 31243
  ingress:
    host: post-service-minio-prod.local
  volume:
    storagePath: /post-service/minio-storage-prod


ingress:
  host: post-service-prod.local